select ID,DERSAD, OGRETMEN.AD +' '+OGRETMEN.SOYAD AS 'ÖÐRETMEN',TARIH,SAAT,DURUM from tbletut  inner join TBLDERSLER
ON
TBLETUT.DERSID=TBLDERSLER.DERSID
inner join TBLOGRETMEN AS OGRETMEN
ON
TBLETUT.OGRETMENID=OGRETMEN.OGRTID




